Fix viewpager testapp
Add a workaround for b/262583150 that causes test run fail with
java.lang.NoSuchMethodError: No static method forceEnableAppTracing()V in class Landroidx/tracing/Trace

Test: run test in FTL API 30
Change-Id: Ieee551820745fdc1fe65190d0f6149203b2f93e1