Fix threading issues in RecyclerViewSmoothScrollToPositionTest
RecyclerViewSmoothScrollToPositionTest#smoothScroll_whenSmoothScrollerStops_destinationReached
was failing with
java.lang.AssertionError: smoothScrollToPosition should succeed (first visible item: 27, last visible item: 32)

This is likely due to the assertions occurring off the main thread,
given the fact that findViewHolderForLayoutPosition relies on the
internal state of ChildHelper, which is updated during layout and
thus could have weird incorrect state if read from off the UI thread.

Bug: 291327689
Test: Ran smoothScroll_whenSmoothScrollerStops_destinationReached
locally and verified that it still passes.

Change-Id: Ief592e4f77c41a8dde950a3202dbae680699ddb1