Partially revert "Close test database in all WorkManager tests"
This reverts commit d6449da621c8c4d4d2aa83914138d8aa8765989e.

Reason for revert: LazyColumn tests started flaking with error "Cannot perform this operation because the connection pool has been closed.
java.lang.IllegalStateException: Cannot perform this operation because the connection pool has been closed."

Change-Id: Ib2f4dac3ce579cc96de69fda59c104590e6ef02c