Replace mockito in Camera2CameraImplTest tests with NoClassDefFoundError
Some tests are failing due to a dexmaker issue of older mockito version
and updating mockito to latest version causes different problem.
Also, mockito is no longer recommended for androidx, so mockito usage is being
removed from these tests and they are being tested manually while keeping the behavior same.

Bug: b/239752223
Test: ./gradlew bOS
Change-Id: I6d208d02faa7581185004b3f710ef6136dd36e2a