Change Void -> Void? in OutcomeReceiver to avoid NPE
In kotlin, Void is not instantiable, the only candidate is `null` which is of type `Void?`.

The current code causes a NPE when invoked from kotlin:

java.lang.NullPointerException: Parameter specified as non-null is null: method androidx.wear.remote.interactions.RemoteActivityHelper$startRemoteActivity$1$1.onResult, parameter result
     at androidx.wear.remote.interactions.RemoteActivityHelper$startRemoteActivity$1$1.onResult(Unknown Source:2)

I am assuming the API is not changeable, clients will have to cast the result of the call to ListenableFuture<Void?>.

Bug: 412727847
Test: ./gradlew :wear:wear-remote-interactions:test
Change-Id: I12c44b17485a52ab9b1c682ebcb70c72466b4ddf