Revert "Bump androidx.test.core to 1.4.0"
This reverts commit d8aebc4b6910b8d867836cf02dfae274c6ccd3c8.

Reason for revert: Broke a number of @LargeTest across the codebase.
Example https://android-build.googleplex.com/builds/tests/view?invocationId=I63900009972892409

It seems to be missing some of upgrades to 1.4.0
java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/test/internal/platform/app/ActivityInvoker$-CC;

Change-Id: Ia36bd5712921fa081fcba16886aa148a76cff20d