Fix CameraX-on-Pipe extensions issue on Xiaomi 15
Accessing the following CameraExtensionCharacteristics methods can cause NoSuchMethodError. Apps side can't catch the error. Added the quirks and workaround to not access these two functions and directly returning false.
 - isPostviewAvailable
 - isCaptureProcessProgressAvailable

Accessing the following CameraExtensionsCharacteristics method can cause IllegalArgumentationException. Try-catch it to avoid the malfunction.
 - getAvailableCaptureRequestKeys

Bug: 425225593
Test: manual test

Change-Id: Iab03421aba4bf5126a9f00148a1d3c1169ba5c79