Revert "Migrate camera to mockito 4"
This reverts commit 3f57befeacf2d48550e0f4beba715f403cb09338.

- Keep the MockitoCore4 declaration in libs.versions.toml

Reason for revert: Mockito 4 causes NoSuchMethodError when using verify() function on API level 23 or lower devices. Enabling desugaring can fix the test failures. But it might force developers to also enable desugaring if the library implementation accidentally uses Java 8+ desugaring API.

Bug: 248209002
Test: Run some tests with verify() calls on a API level 23 device

Change-Id: Ia2e5e132d8cae898652da5c91c78516df613884c