Fix lint error that broke the bud in aosp/1087693
Error:

/Users/xizh/Workspace/androidx-master-dev/frameworks/support/camera/camera-core/src/main/java/androidx/camera/core/ImageAnalysis.java:278: Error: Access to private field mHandler of class ImageAnalysis requires synthetic accessor [SyntheticAccessor]
                        mHandler.post(new Runnable() {
                        ~~~~~~~~

Bug: 121349926
Test: ./gradlew camera:connectedCheck
Change-Id: If5445fde3b28adb7194ee225e92abf6bde00f8d0